# Generated by Django 5.1.1 on 2024-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/user/defaultuser/defuser.png', upload_to='user/images/'),
        ),
    ]
