# Generated by Django 5.1.1 on 2024-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/user/defaultuser/defuser.png', null=True, upload_to='user/images/'),
        ),
    ]
